apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-scan
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: scan
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: teams/team-scan/dev
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  helm:
      values: |
        spec:
          repositoryUri: {{ index .Values.spec "repositoryUri" }}
          region: {{ index .Values.spec "region" }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
