apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-encrypted
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: efs.csi.aws.com
mountOptions:
  - tls
parameters:
  fileSystemId: {{ .Values.spec.fileSystemId }}
  accessPointId: fsap-080c9ab37df498963
  provisioningMode: efs-ap
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-storage-class
spec:
  template:
    spec:
      containers:
      - name: wait-for-storage-class
        image: busybox
        command: ['sh', '-c', 'until kubectl get sc efs-encrypted > /dev/null 2>&1; do sleep 1; done']
      restartPolicy: Never
  backoffLimit: 0
