apiVersion: efs.csi.aws.com/v1alpha1
kind: EFSAccessPoint
metadata:
  name: efs-access-point
spec:
  accessPointID: {{ .Values.spec.accessPointID }}
  fileSystemID: {{ .Values.spec.fileSystemId }}
  posixUser:
    uid: 1000
    gid: 1000
  rootDirectory:
    path: /efs-access-point
    creationInfo:
      ownerUID: 1000
      ownerGID: 1000
      permissions: "777"
