apiVersion: efs.csi.aws.com/v1alpha1
kind: EFSAccessPoint
metadata:
  name: efs-encrypted
spec:
  fileSystemId: {{ .Values.spec.fileSystemId }}
  posixUser:
    gid: 1000
    uid: 1000
  rootDirectory:
    path: "/"
    creationInfo:
      ownerGid: 1000
      ownerUid: 1000
      permissions: "777"
