kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-encrypted
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: efs.csi.aws.com
mountOptions:
  - tls
parameters:
  fileSystemId: {{ .Values.spec.fileSystemId }}
  accessPointId: fsap-01553073196ee5983
  provisioningMode: efs-ap
