kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-encrypted
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: efs.csi.aws.com
mountOptions:
  - tls
parameters:
  provisioningMode: efs-ap
{{ if .Values.spec.kmsKey }}
  kmsKeyId: {{ .Values.spec.kmsKey }} # The KMS key ID to use for encryption, otherwise the default key (AWS-managed) is used
{{ end }}
