kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-encrypted
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
  {{ if .Values.spec.kmsKey }}
    kmsKeyId: { { .Values.spec.kmsKey.keyArn } }
  {{ end }}
